/**
 * TemplateProcessor - Process template files with variable replacement
 * Reads templates from disk and replaces variables before creating files
 */

import { App, TFile, Notice } from 'obsidian';

export interface TemplateVariables {
  [key: string]: string | number | undefined;
}

export class TemplateProcessor {
  constructor(private app: App) {}

  /**
   * Get available templates
   */
  async getAvailableTemplates(templatesFolder: string): Promise<string[]> {
    try {
      const folder = this.app.vault.getAbstractFileByPath(templatesFolder);
      if (!folder || !('children' in folder)) {
        console.warn(`[TemplateProcessor] Templates folder not found: ${templatesFolder}`);
        return [];
      }

      const templates: string[] = [];
      for (const file of (folder as any).children) {
        if (file.name.startsWith('template-') && file.name.endsWith('.md')) {
          templates.push(file.name);
        }
      }
      return templates;
    } catch (error) {
      console.error('[TemplateProcessor] Error getting templates:', error);
      return [];
    }
  }

  /**
   * Read and process a template file
   */
  async processTemplate(
    templateName: string,
    templatesFolder: string,
    variables: TemplateVariables
  ): Promise<string> {
    try {
      const templatePath = `${templatesFolder}/${templateName}`;
      const templateFile = this.app.vault.getAbstractFileByPath(templatePath);

      if (!templateFile || 'children' in templateFile) {
        throw new Error(`Template not found: ${templatePath}`);
      }

      // Read template content
      let content = await this.app.vault.read(templateFile as TFile);

      // Replace VALUE variables: {{VALUE:key}} → value
      for (const [key, value] of Object.entries(variables)) {
        if (value !== undefined) {
          const regex = new RegExp(`{{VALUE:${key}}}`, 'g');
          content = content.replace(regex, String(value));
        }
      }

      // Remove any unreplaced variables
      content = content.replace(/{{VALUE:[^}]+}}/g, '');

      return content;
    } catch (error) {
      console.error('[TemplateProcessor] Error processing template:', error);
      throw error;
    }
  }

  /**
   * Get template for entity type
   */
  getTemplateForType(type: 'project' | 'task' | 'objective' | 'document'): string {
    const templates: Record<string, string> = {
      project: 'template-project.md',
      task: 'template-task.md',
      objective: 'template-objective.md',
      document: 'template-nota.md',
    };
    return templates[type];
  }

  /**
   * Create file from template
   */
  async createFileFromTemplate(
    filePath: string,
    templateName: string,
    templatesFolder: string,
    variables: TemplateVariables
  ): Promise<TFile> {
    try {
      // Process template with variables
      const content = await this.processTemplate(templateName, templatesFolder, variables);

      // Create file
      const file = await this.app.vault.create(filePath, content);

      if (this.app.workspace.getActiveFile() === null) {
        // Open file if no file is active
        const leaf = this.app.workspace.getLeaf();
        await leaf?.openFile(file);
      }

      return file;
    } catch (error) {
      console.error('[TemplateProcessor] Error creating file from template:', error);
      throw error;
    }
  }

  /**
   * Process template content (for dynamic content generation)
   * Can be used to generate README or other dynamic files
   */
  processContent(
    template: string,
    variables: TemplateVariables
  ): string {
    let content = template;

    // Replace VALUE variables
    for (const [key, value] of Object.entries(variables)) {
      if (value !== undefined) {
        const regex = new RegExp(`{{VALUE:${key}}}`, 'g');
        content = content.replace(regex, String(value));
      }
    }

    // Remove unreplaced variables
    content = content.replace(/{{VALUE:[^}]+}}/g, '');

    return content;
  }

  /**
   * Generate README content from template
   */
  generateReadmeContent(
    title: string,
    description: string,
    type: string,
    dateCreated: string,
    priority?: string
  ): string {
    const priorityLine = priority ? `\n- **Priority**: ${priority}` : '';

    return `---
type: ${type}
title: ${title}
description: ${description}
dateCreated: ${dateCreated}
status: active
---

# ${title}

## Description

${description}

## Details

- **Type**: ${type}
- **Created**: ${dateCreated}${priorityLine}
- **Status**: Active

## Sections

### Quick Links
- Browse related items
- View sub-items
- Archive when done

---

*Generated by Chronex Obsidian*
`;
  }
}
